### ISSUE TITLE
aggregations to dataframe always misses the first pagination

### ISSUE THREAD

**Issue by Andy7475** [alkemics/pandagg#101]
Hi,
This is a really useful package, thank you! I noticed though that scan_composite_agg has a bug. It misses the first page of aggregations. I think it is because you declare variable 'buckets', enter while loop, re-declare it, then iterate over it. So the *first* version of buckets never has a chance to be iterated over, which is why I presume we always miss the 1st pagination. . Hope that makes sense, think you just need to move a line

***YOU DECLARE BUCKETS HERE***
buckets: List[BucketDict] = r.aggregations.data[a_name][  # type: ignore
            "buckets"
        ]
        after_key: AfterKey = r.aggregations.data[a_name]["after_key"]  # type: ignore

        init: bool = True
        while init or len(buckets) == size:
            init = False
            s._aggs = s._aggs.as_composite(size=size, after=after_key)
            r = s.execute()
            agg_clause_response = r.aggregations.data[a_name]

***THEN CHANGE IT HERE, BEFORE YOU HAVE HAD A CHANCE TO ITERATE OVER THE OLD ONE***
            buckets = agg_clause_response["buckets"]  # type: ignore  ****MOVE THIS LINE TO LATER
            for bucket in buckets:

**Comment by leonardbinet** [comment]
Hi @Andy7475 , thanks for finding this bug 👍 I'll merge the fix as soon as I regain admin rights on this repo.

**Comment by leonardbinet** [comment]
@Andy7475  fixes/features are available on  pandagg `0.2.4` version (https://github.com/alkemics/pandagg/pull/115)

**Comment by Andy7475** [comment]
Hi Leonard, I can see you have modified the code, but doing 'pip install
pandagg' is still pulling the old code with the error for some reason (even
with 0.2.4); I am modifying it locally for the time being.

Just thought you would like to know :)
Andy

**Comment by Andy7475** [comment]
Subject: Request for a new release of Pandagg on PyPI

Hi Leonard,
I hope this email finds you well. I was trying to install the latest version of the package via pip, but I noticed that the version on PyPI (0.2.4) is not the same as the latest release on GitHub master branch (0.2.1). 0.2.4 [dev branch] has a bug in search.py file with the line starting raw_data =..., but the master branch looks good.

I was wondering if it would be possible for you to publish a new version of the package from the master branch to PyPI, so that users can easily install the latest version using pip.

I understand that this may not be a priority for you, and I would be happy to assist in any way that I can. If there is anything I can do to help, please let me know.

Thank you for your time and for maintaining such a valuable package. I look forward to your response.

All the best,

Andy
