### ISSUE TITLE
NotImplementedError: DSL class `ip_range` does not exist in field.

### ISSUE THREAD

**Issue by priamai** [alkemics/pandagg#80]
Hi there,
I have ingested some simple filebeat logs (v 7.14.0) and when I try this:

```
indices = discover(client, "filebeat-*")
NotImplementedError: DSL class `ip_range` does not exist in field.
```

In the file mappings I do see indeed a field called ip_range, I wonder if this is a problem related to the python elastic DSL library?

**Comment by alk-lbinet** [comment]
The `ip_range` field type was missing in `pandagg` field types, I've created the PR to fix this

**Comment by alk-lbinet** [comment]
should be ok with pandagg version `0.2.2`

**Comment by robomotic** [comment]
Will test asap, awesome.

**Comment by priamai** [comment]
Working and closing!
